# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compose-tests:
    runs-on: ubuntu-latest

    # Segredos viram variáveis de ambiente que o docker-compose consome
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      ENV: ci          # força modo CI no app

    steps:

      # Copia repositório para VM
      - uses: actions/checkout@v4

      # Builda as imagens declaradas no docker-compose.yml
      - name: Build images
        run: docker compose build --quiet   # --quiet reduz ruído de log

      # Roda todos os tests/ dentro do serviço backend
      - name: Run unit tests
        run: docker compose run --rm backend python -m unittest discover -s tests -v

      # Limpa tudo mesmo se algum passo falhar
      - name: Clean up
        if: always()
        run: docker compose down --volumes --remove-orphans
