name: Build & Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU & Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: docker.io                 # ou ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: app/Dockerfile.app
          push: true
          tags: ${{ secrets.REGISTRY_USER }}/ml-deploy-test:latest
          build-args: |
            MONGO_URI=${{ secrets.MONGO_URI }}
            WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}
            ATLAS_KEY=${{ secrets.ATLAS_KEY }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify push
        run: |
          echo "Imagem publicada em ${{ secrets.REGISTRY_USER }}/ml-deploy-test:latest"
